#!/usr/bin/env python
""" This is an alternative to pythoni which tries to look like the
CPython prompt as much as possible, with the exception of allowing
multiline input and multiline history entries.
"""

import os, sys
from pyrepl import readline
from pyrepl.simple_interact import run_multiline_interactive_console

sys.modules['readline'] = readline

if os.getenv('PYTHONSTARTUP'):
    execfile(os.getenv('PYTHONSTARTUP'))

print 'Python', sys.version
run_multiline_interactive_console()
